// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:my_first_app/config/config.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
      authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? '',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? '',
      storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? '',
      messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '',
      appId: dotenv.env['FIREBASE_APP_ID'] ?? '',
      measurementId: dotenv.env['FIREBASE_MEASUREMENT_ID'] ?? '',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ZuC5C11gqr_itXayW3uUXW2VKNaY69o',
    appId: '1:200941976223:web:6c09de56ac5c19ef0c40aa',
    messagingSenderId: '200941976223',
    projectId: 'fridgeai-9fa1f',
    authDomain: 'fridgeai-9fa1f.firebaseapp.com',
    storageBucket: 'fridgeai-9fa1f.firebasestorage.app',
    measurementId: 'G-BSDHJMTG4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4EER7gh7J5G51UdRCMagH-km7rDMBIYM',
    appId: '1:200941976223:android:1375381883bee6b00c40aa',
    messagingSenderId: '200941976223',
    projectId: 'fridgeai-9fa1f',
    storageBucket: 'fridgeai-9fa1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdlkP91HOkWFmZLU1oMSl5WjZbjoU8xpI',
    appId: '1:200941976223:ios:4df97c8be8132b330c40aa',
    messagingSenderId: '200941976223',
    projectId: 'fridgeai-9fa1f',
    storageBucket: 'fridgeai-9fa1f.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdlkP91HOkWFmZLU1oMSl5WjZbjoU8xpI',
    appId: '1:200941976223:ios:4df97c8be8132b330c40aa',
    messagingSenderId: '200941976223',
    projectId: 'fridgeai-9fa1f',
    storageBucket: 'fridgeai-9fa1f.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ZuC5C11gqr_itXayW3uUXW2VKNaY69o',
    appId: '1:200941976223:web:6ed2312cf00e23940c40aa',
    messagingSenderId: '200941976223',
    projectId: 'fridgeai-9fa1f',
    authDomain: 'fridgeai-9fa1f.firebaseapp.com',
    storageBucket: 'fridgeai-9fa1f.firebasestorage.app',
    measurementId: 'G-5SE91N7Z9R',
  );
}
