// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ZuC5C11gqr_itXayW3uUXW2VKNaY69o',
    appId: '1:200941976223:web:6c09de56ac5c19ef0c40aa',
    messagingSenderId: '200941976223',
    projectId: 'fridgeai-9fa1f',
    authDomain: 'fridgeai-9fa1f.firebaseapp.com',
    storageBucket: 'fridgeai-9fa1f.firebasestorage.app',
    measurementId: 'G-BSDHJMTG4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4EER7gh7J5G51UdRCMagH-km7rDMBIYM',
    appId: '1:200941976223:android:1375381883bee6b00c40aa',
    messagingSenderId: '200941976223',
    projectId: 'fridgeai-9fa1f',
    storageBucket: 'fridgeai-9fa1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdlkP91HOkWFmZLU1oMSl5WjZbjoU8xpI',
    appId: '1:200941976223:ios:4df97c8be8132b330c40aa',
    messagingSenderId: '200941976223',
    projectId: 'fridgeai-9fa1f',
    storageBucket: 'fridgeai-9fa1f.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdlkP91HOkWFmZLU1oMSl5WjZbjoU8xpI',
    appId: '1:200941976223:ios:4df97c8be8132b330c40aa',
    messagingSenderId: '200941976223',
    projectId: 'fridgeai-9fa1f',
    storageBucket: 'fridgeai-9fa1f.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ZuC5C11gqr_itXayW3uUXW2VKNaY69o',
    appId: '1:200941976223:web:6ed2312cf00e23940c40aa',
    messagingSenderId: '200941976223',
    projectId: 'fridgeai-9fa1f',
    authDomain: 'fridgeai-9fa1f.firebaseapp.com',
    storageBucket: 'fridgeai-9fa1f.firebasestorage.app',
    measurementId: 'G-5SE91N7Z9R',
  );

}